name: lte_lock
description: "Aplikasi Flutter untuk mengakses informasi radio/telephony yang menggantikan menu *#*#4636#*#*"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  android_intent_plus: ^5.3.1
  permission_handler: ^12.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
